language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

os:
  - linux
#  - osx

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
    - cd zan-extension
    - phpize
    - ./configure --enable-sockets --enable-async-redis --enable-openssl
    - make clean
    - make
    - make install

script:
    - exit 0
